#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webII")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_producto(Tbl_producto instance);
    partial void UpdateTbl_producto(Tbl_producto instance);
    partial void DeleteTbl_producto(Tbl_producto instance);
    partial void InsertTbl_proveedor(Tbl_proveedor instance);
    partial void UpdateTbl_proveedor(Tbl_proveedor instance);
    partial void DeleteTbl_proveedor(Tbl_proveedor instance);
    partial void InsertTbl_TipoUsuario(Tbl_TipoUsuario instance);
    partial void UpdateTbl_TipoUsuario(Tbl_TipoUsuario instance);
    partial void DeleteTbl_TipoUsuario(Tbl_TipoUsuario instance);
    partial void InsertTbl_Usuario(Tbl_Usuario instance);
    partial void UpdateTbl_Usuario(Tbl_Usuario instance);
    partial void DeleteTbl_Usuario(Tbl_Usuario instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CapaDato.Properties.Settings.Default.webIIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_producto> Tbl_producto
		{
			get
			{
				return this.GetTable<Tbl_producto>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_proveedor> Tbl_proveedor
		{
			get
			{
				return this.GetTable<Tbl_proveedor>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_TipoUsuario> Tbl_TipoUsuario
		{
			get
			{
				return this.GetTable<Tbl_TipoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this.GetTable<Tbl_Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_producto")]
	public partial class Tbl_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private System.Nullable<int> _pro_cantidad;
		
		private System.Nullable<char> _pro_estado;
		
		private int _prov_id;
		
		private EntityRef<Tbl_proveedor> _Tbl_proveedor;
		
		private EntityRef<Tbl_proveedor> _Tbl_proveedor1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_cantidadChanging(System.Nullable<int> value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_estadoChanging(System.Nullable<char> value);
    partial void Onpro_estadoChanged();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    #endregion
		
		public Tbl_producto()
		{
			this._Tbl_proveedor = default(EntityRef<Tbl_proveedor>);
			this._Tbl_proveedor1 = default(EntityRef<Tbl_proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="VarChar(50)")]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int")]
		public System.Nullable<int> pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Char(1)")]
		public System.Nullable<char> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int NOT NULL")]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					if ((this._Tbl_proveedor.HasLoadedOrAssignedValue || this._Tbl_proveedor1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_proveedor_Tbl_producto", Storage="_Tbl_proveedor", ThisKey="prov_id", OtherKey="prov_id", IsForeignKey=true)]
		public Tbl_proveedor Tbl_proveedor
		{
			get
			{
				return this._Tbl_proveedor.Entity;
			}
			set
			{
				Tbl_proveedor previousValue = this._Tbl_proveedor.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_proveedor.Entity = null;
						previousValue.Tbl_producto.Remove(this);
					}
					this._Tbl_proveedor.Entity = value;
					if ((value != null))
					{
						value.Tbl_producto.Add(this);
						this._prov_id = value.prov_id;
					}
					else
					{
						this._prov_id = default(int);
					}
					this.SendPropertyChanged("Tbl_proveedor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_proveedor_Tbl_producto1", Storage="_Tbl_proveedor1", ThisKey="prov_id", OtherKey="prov_id", IsForeignKey=true)]
		public Tbl_proveedor Tbl_proveedor1
		{
			get
			{
				return this._Tbl_proveedor1.Entity;
			}
			set
			{
				Tbl_proveedor previousValue = this._Tbl_proveedor1.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_proveedor1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_proveedor1.Entity = null;
						previousValue.Tbl_producto1.Remove(this);
					}
					this._Tbl_proveedor1.Entity = value;
					if ((value != null))
					{
						value.Tbl_producto1.Add(this);
						this._prov_id = value.prov_id;
					}
					else
					{
						this._prov_id = default(int);
					}
					this.SendPropertyChanged("Tbl_proveedor1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_proveedor")]
	public partial class Tbl_proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private string _prov_nombre;
		
		private System.Nullable<char> _prov_estado;
		
		private EntitySet<Tbl_producto> _Tbl_producto;
		
		private EntitySet<Tbl_producto> _Tbl_producto1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Onprov_nombreChanging(string value);
    partial void Onprov_nombreChanged();
    partial void Onprov_estadoChanging(System.Nullable<char> value);
    partial void Onprov_estadoChanged();
    #endregion
		
		public Tbl_proveedor()
		{
			this._Tbl_producto = new EntitySet<Tbl_producto>(new Action<Tbl_producto>(this.attach_Tbl_producto), new Action<Tbl_producto>(this.detach_Tbl_producto));
			this._Tbl_producto1 = new EntitySet<Tbl_producto>(new Action<Tbl_producto>(this.attach_Tbl_producto1), new Action<Tbl_producto>(this.detach_Tbl_producto1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_nombre", DbType="VarChar(50)")]
		public string prov_nombre
		{
			get
			{
				return this._prov_nombre;
			}
			set
			{
				if ((this._prov_nombre != value))
				{
					this.Onprov_nombreChanging(value);
					this.SendPropertyChanging();
					this._prov_nombre = value;
					this.SendPropertyChanged("prov_nombre");
					this.Onprov_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_estado", DbType="Char(1)")]
		public System.Nullable<char> prov_estado
		{
			get
			{
				return this._prov_estado;
			}
			set
			{
				if ((this._prov_estado != value))
				{
					this.Onprov_estadoChanging(value);
					this.SendPropertyChanging();
					this._prov_estado = value;
					this.SendPropertyChanged("prov_estado");
					this.Onprov_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_proveedor_Tbl_producto", Storage="_Tbl_producto", ThisKey="prov_id", OtherKey="prov_id")]
		public EntitySet<Tbl_producto> Tbl_producto
		{
			get
			{
				return this._Tbl_producto;
			}
			set
			{
				this._Tbl_producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_proveedor_Tbl_producto1", Storage="_Tbl_producto1", ThisKey="prov_id", OtherKey="prov_id")]
		public EntitySet<Tbl_producto> Tbl_producto1
		{
			get
			{
				return this._Tbl_producto1;
			}
			set
			{
				this._Tbl_producto1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_producto(Tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_proveedor = this;
		}
		
		private void detach_Tbl_producto(Tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_proveedor = null;
		}
		
		private void attach_Tbl_producto1(Tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_proveedor1 = this;
		}
		
		private void detach_Tbl_producto1(Tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_proveedor1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_TipoUsuario")]
	public partial class Tbl_TipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Tusu_id;
		
		private string _Tusu_nombre;
		
		private System.Nullable<char> _Tusu_estado;
		
		private EntitySet<Tbl_Usuario> _Tbl_Usuario;
		
		private EntitySet<Tbl_Usuario> _Tbl_Usuario1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTusu_idChanging(int value);
    partial void OnTusu_idChanged();
    partial void OnTusu_nombreChanging(string value);
    partial void OnTusu_nombreChanged();
    partial void OnTusu_estadoChanging(System.Nullable<char> value);
    partial void OnTusu_estadoChanged();
    #endregion
		
		public Tbl_TipoUsuario()
		{
			this._Tbl_Usuario = new EntitySet<Tbl_Usuario>(new Action<Tbl_Usuario>(this.attach_Tbl_Usuario), new Action<Tbl_Usuario>(this.detach_Tbl_Usuario));
			this._Tbl_Usuario1 = new EntitySet<Tbl_Usuario>(new Action<Tbl_Usuario>(this.attach_Tbl_Usuario1), new Action<Tbl_Usuario>(this.detach_Tbl_Usuario1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tusu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Tusu_id
		{
			get
			{
				return this._Tusu_id;
			}
			set
			{
				if ((this._Tusu_id != value))
				{
					this.OnTusu_idChanging(value);
					this.SendPropertyChanging();
					this._Tusu_id = value;
					this.SendPropertyChanged("Tusu_id");
					this.OnTusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tusu_nombre", DbType="VarChar(100)")]
		public string Tusu_nombre
		{
			get
			{
				return this._Tusu_nombre;
			}
			set
			{
				if ((this._Tusu_nombre != value))
				{
					this.OnTusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._Tusu_nombre = value;
					this.SendPropertyChanged("Tusu_nombre");
					this.OnTusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tusu_estado", DbType="Char(1)")]
		public System.Nullable<char> Tusu_estado
		{
			get
			{
				return this._Tusu_estado;
			}
			set
			{
				if ((this._Tusu_estado != value))
				{
					this.OnTusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._Tusu_estado = value;
					this.SendPropertyChanged("Tusu_estado");
					this.OnTusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_TipoUsuario_Tbl_Usuario", Storage="_Tbl_Usuario", ThisKey="Tusu_id", OtherKey="Tusu_id")]
		public EntitySet<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this._Tbl_Usuario;
			}
			set
			{
				this._Tbl_Usuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_TipoUsuario_Tbl_Usuario1", Storage="_Tbl_Usuario1", ThisKey="Tusu_id", OtherKey="Tusu_id")]
		public EntitySet<Tbl_Usuario> Tbl_Usuario1
		{
			get
			{
				return this._Tbl_Usuario1;
			}
			set
			{
				this._Tbl_Usuario1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Usuario(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_TipoUsuario = this;
		}
		
		private void detach_Tbl_Usuario(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_TipoUsuario = null;
		}
		
		private void attach_Tbl_Usuario1(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_TipoUsuario1 = this;
		}
		
		private void detach_Tbl_Usuario1(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_TipoUsuario1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Usuario")]
	public partial class Tbl_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Usu_id;
		
		private string _Usu_cedula;
		
		private string _Usu_nombre;
		
		private string _Usu_apellido;
		
		private string _Usu_direccion;
		
		private string _Usu_telefono;
		
		private System.Nullable<System.DateTime> _Usu_fechacreacion;
		
		private string _Usu_contraseña;
		
		private string _Usu_nomlogin;
		
		private System.Nullable<char> _Usu_estado;
		
		private string _Usu_correo;
		
		private int _Tusu_id;
		
		private EntityRef<Tbl_TipoUsuario> _Tbl_TipoUsuario;
		
		private EntityRef<Tbl_TipoUsuario> _Tbl_TipoUsuario1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsu_idChanging(int value);
    partial void OnUsu_idChanged();
    partial void OnUsu_cedulaChanging(string value);
    partial void OnUsu_cedulaChanged();
    partial void OnUsu_nombreChanging(string value);
    partial void OnUsu_nombreChanged();
    partial void OnUsu_apellidoChanging(string value);
    partial void OnUsu_apellidoChanged();
    partial void OnUsu_direccionChanging(string value);
    partial void OnUsu_direccionChanged();
    partial void OnUsu_telefonoChanging(string value);
    partial void OnUsu_telefonoChanged();
    partial void OnUsu_fechacreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnUsu_fechacreacionChanged();
    partial void OnUsu_contraseñaChanging(string value);
    partial void OnUsu_contraseñaChanged();
    partial void OnUsu_nomloginChanging(string value);
    partial void OnUsu_nomloginChanged();
    partial void OnUsu_estadoChanging(System.Nullable<char> value);
    partial void OnUsu_estadoChanged();
    partial void OnUsu_correoChanging(string value);
    partial void OnUsu_correoChanged();
    partial void OnTusu_idChanging(int value);
    partial void OnTusu_idChanged();
    #endregion
		
		public Tbl_Usuario()
		{
			this._Tbl_TipoUsuario = default(EntityRef<Tbl_TipoUsuario>);
			this._Tbl_TipoUsuario1 = default(EntityRef<Tbl_TipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Usu_id
		{
			get
			{
				return this._Usu_id;
			}
			set
			{
				if ((this._Usu_id != value))
				{
					this.OnUsu_idChanging(value);
					this.SendPropertyChanging();
					this._Usu_id = value;
					this.SendPropertyChanged("Usu_id");
					this.OnUsu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_cedula", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usu_cedula
		{
			get
			{
				return this._Usu_cedula;
			}
			set
			{
				if ((this._Usu_cedula != value))
				{
					this.OnUsu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._Usu_cedula = value;
					this.SendPropertyChanged("Usu_cedula");
					this.OnUsu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usu_nombre
		{
			get
			{
				return this._Usu_nombre;
			}
			set
			{
				if ((this._Usu_nombre != value))
				{
					this.OnUsu_nombreChanging(value);
					this.SendPropertyChanging();
					this._Usu_nombre = value;
					this.SendPropertyChanged("Usu_nombre");
					this.OnUsu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usu_apellido
		{
			get
			{
				return this._Usu_apellido;
			}
			set
			{
				if ((this._Usu_apellido != value))
				{
					this.OnUsu_apellidoChanging(value);
					this.SendPropertyChanging();
					this._Usu_apellido = value;
					this.SendPropertyChanged("Usu_apellido");
					this.OnUsu_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_direccion", DbType="VarChar(50)")]
		public string Usu_direccion
		{
			get
			{
				return this._Usu_direccion;
			}
			set
			{
				if ((this._Usu_direccion != value))
				{
					this.OnUsu_direccionChanging(value);
					this.SendPropertyChanging();
					this._Usu_direccion = value;
					this.SendPropertyChanged("Usu_direccion");
					this.OnUsu_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_telefono", DbType="VarChar(50)")]
		public string Usu_telefono
		{
			get
			{
				return this._Usu_telefono;
			}
			set
			{
				if ((this._Usu_telefono != value))
				{
					this.OnUsu_telefonoChanging(value);
					this.SendPropertyChanging();
					this._Usu_telefono = value;
					this.SendPropertyChanged("Usu_telefono");
					this.OnUsu_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_fechacreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Usu_fechacreacion
		{
			get
			{
				return this._Usu_fechacreacion;
			}
			set
			{
				if ((this._Usu_fechacreacion != value))
				{
					this.OnUsu_fechacreacionChanging(value);
					this.SendPropertyChanging();
					this._Usu_fechacreacion = value;
					this.SendPropertyChanged("Usu_fechacreacion");
					this.OnUsu_fechacreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_contraseña", DbType="VarChar(50)")]
		public string Usu_contraseña
		{
			get
			{
				return this._Usu_contraseña;
			}
			set
			{
				if ((this._Usu_contraseña != value))
				{
					this.OnUsu_contraseñaChanging(value);
					this.SendPropertyChanging();
					this._Usu_contraseña = value;
					this.SendPropertyChanged("Usu_contraseña");
					this.OnUsu_contraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_nomlogin", DbType="VarChar(50)")]
		public string Usu_nomlogin
		{
			get
			{
				return this._Usu_nomlogin;
			}
			set
			{
				if ((this._Usu_nomlogin != value))
				{
					this.OnUsu_nomloginChanging(value);
					this.SendPropertyChanging();
					this._Usu_nomlogin = value;
					this.SendPropertyChanged("Usu_nomlogin");
					this.OnUsu_nomloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_estado", DbType="Char(1)")]
		public System.Nullable<char> Usu_estado
		{
			get
			{
				return this._Usu_estado;
			}
			set
			{
				if ((this._Usu_estado != value))
				{
					this.OnUsu_estadoChanging(value);
					this.SendPropertyChanging();
					this._Usu_estado = value;
					this.SendPropertyChanged("Usu_estado");
					this.OnUsu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_correo", DbType="VarChar(50)")]
		public string Usu_correo
		{
			get
			{
				return this._Usu_correo;
			}
			set
			{
				if ((this._Usu_correo != value))
				{
					this.OnUsu_correoChanging(value);
					this.SendPropertyChanging();
					this._Usu_correo = value;
					this.SendPropertyChanged("Usu_correo");
					this.OnUsu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tusu_id", DbType="Int NOT NULL")]
		public int Tusu_id
		{
			get
			{
				return this._Tusu_id;
			}
			set
			{
				if ((this._Tusu_id != value))
				{
					if ((this._Tbl_TipoUsuario.HasLoadedOrAssignedValue || this._Tbl_TipoUsuario1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTusu_idChanging(value);
					this.SendPropertyChanging();
					this._Tusu_id = value;
					this.SendPropertyChanged("Tusu_id");
					this.OnTusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_TipoUsuario_Tbl_Usuario", Storage="_Tbl_TipoUsuario", ThisKey="Tusu_id", OtherKey="Tusu_id", IsForeignKey=true)]
		public Tbl_TipoUsuario Tbl_TipoUsuario
		{
			get
			{
				return this._Tbl_TipoUsuario.Entity;
			}
			set
			{
				Tbl_TipoUsuario previousValue = this._Tbl_TipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_TipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_TipoUsuario.Entity = null;
						previousValue.Tbl_Usuario.Remove(this);
					}
					this._Tbl_TipoUsuario.Entity = value;
					if ((value != null))
					{
						value.Tbl_Usuario.Add(this);
						this._Tusu_id = value.Tusu_id;
					}
					else
					{
						this._Tusu_id = default(int);
					}
					this.SendPropertyChanged("Tbl_TipoUsuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_TipoUsuario_Tbl_Usuario1", Storage="_Tbl_TipoUsuario1", ThisKey="Tusu_id", OtherKey="Tusu_id", IsForeignKey=true)]
		public Tbl_TipoUsuario Tbl_TipoUsuario1
		{
			get
			{
				return this._Tbl_TipoUsuario1.Entity;
			}
			set
			{
				Tbl_TipoUsuario previousValue = this._Tbl_TipoUsuario1.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_TipoUsuario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_TipoUsuario1.Entity = null;
						previousValue.Tbl_Usuario1.Remove(this);
					}
					this._Tbl_TipoUsuario1.Entity = value;
					if ((value != null))
					{
						value.Tbl_Usuario1.Add(this);
						this._Tusu_id = value.Tusu_id;
					}
					else
					{
						this._Tusu_id = default(int);
					}
					this.SendPropertyChanged("Tbl_TipoUsuario1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
